# Generated by Django 5.2.9 on 2026-01-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_alter_pokemonentity_pokemon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Appeared_at',
            new_name='appeared_at',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Attack',
            new_name='attack',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Defense',
            new_name='defense',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Disappeared_at',
            new_name='disappeared_at',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Health',
            new_name='health',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Pokemon',
            new_name='pokemon_model',
        ),
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Stamina',
            new_name='stamina',
        ),
    ]
